apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: "gcr.io/chabunsi-project/auth"
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/auth"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: JWT_KEY
          resources:
            requests:
              cpu: 500m
              memory: 0.7G
            limits:
              cpu: 1
              memory: 1.5G
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000

