apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  selector:
    matchLabels:
      app: orders
  replicas: 1
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: "gcr.io/chabunsi-project/orders"
          resources:
            requests:
              cpu: 500m
              memory: 0.7G
            limits:
              cpu: 1
              memory: 1.5G